# Generated by Django 5.2.5 on 2025-10-23 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cover_media_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-featured', '-start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='mediablob',
            options={'ordering': ['display_order', '-size']},
        ),
        migrations.AddField(
            model_name='event',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='mediablob',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Orden de visualización (menor = primero)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad máxima de asistentes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Mostrar en destacados'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en tu moneda local', max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Título del evento', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(help_text='Nombre del lugar', max_length=200),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created_at', 'status'], name='events_even_created_3ad068_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['featured', '-created_at'], name='events_even_feature_0d1a39_idx'),
        ),
    ]
